name: Build terraform
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    compile:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: 1.7.3
            - name: Terraform Initialize
              run: terraform -chdir="./infra" init
            - name: Terraform Format
              run: terraform -chdir="./infra" fmt
            - name: Terraform Validate
              run: terraform -chdir="./infra" validate
